package davidstan.sbnz.integration;

import davidstan.sbnz.integration.facts.Stocks;
import davidstan.sbnz.integration.facts.Risk;
import davidstan.sbnz.integration.models.Sector;

agenda-group "risk"

global ExternalService externalService;

rule "Test rule"
	lock-on-active
    when
        $r: Risk( )
    then
        System.out.println("Second rulegroup");
        $r.setValid(true);
        update($r);
end